KP-lesson4-task2 completed task number two
GroovSt/kotlin_practice pull request #20
Opened 2024-05-02 13:17 UTC by GroovSt

2024-05-03 15:19 UTC, ievetrovdev requested changes

2024-05-03 15:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +    println("Груз с весом $cargoWeight кг и объемом $cargoVolume л соответствует категории 'Average': ${((cargoWeight >= MIN_WEIGHT) && (cargoWeight <= MAX_WEIGHT)) && (cargoVolume <= MAX_VOLUME)}")
Да, код корректный. Но давай чуть улучшим.
Строки слишком длинные (>120 символов), глазу труднее в них ориентироваться. Часто в компаниях вводят правила форматирования, а также специальные утилиты, которые следят за соблюдением правил.

2024-05-03 15:28 UTC, GroovSt commented on src/main/kotlin/lesson_4/lesson4_task2.kt
> +    println("Груз с весом $cargoWeight кг и объемом $cargoVolume л соответствует категории 'Average': ${((cargoWeight >= MIN_WEIGHT) && (cargoWeight <= MAX_WEIGHT)) && (cargoVolume <= MAX_VOLUME)}")
Каким способом можно улучшить?

2024-05-04 05:49 UTC, ievetrovdev approved these changes

2024-05-04 06:06 UTC, merged