KP-lesson7-task2 completed task number two
GroovSt/kotlin_practice pull request #35
Opened 2024-05-07 03:18 UTC by GroovSt

2024-05-07 16:10 UTC, ievetrovdev requested changes

2024-05-07 16:10 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +        val randomCode = Random.nextInt(1000..9999)
Можно написать более оптимизированно (без лишнего импорта) - (1000..9999).random()
Смущает повторение кода инициализации переменной. Предлагаю переделать через реализацию с помощью do while

2024-05-07 16:32 UTC, GroovSt commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +        val randomCode = Random.nextInt(1000..9999)
Переписал код на do while, но не очень понял смысла) Объясни пожалуйста)

2024-05-08 14:42 UTC, ievetrovdev approved these changes

2024-05-08 14:42 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task2.kt
> +        val randomCode = (1000..9999).random()
Все хорошо, но для большей элегантности предлагаю не инициализировать переменную внутри цикла. Чтобы каждый раз не выделялась память при пересоздании переменной.

     val randomCode = (1000..9999).random()
     var codeEnter: Int

     do {
         println("Ваш код авторизации N: $code")
         println("Введите код")
         codeEnter = readln().toInt()

     } while (codeEnter != code)
     println("Добро пожаловать!")

А welcome message можно просто написать за пределами цикла (после него)

2024-05-09 06:58 UTC, merged