KP-lesson9-task2 completed task number two
GroovSt/kotlin_practice pull request #45
Opened 2024-05-08 11:15 UTC by GroovSt

2024-05-09 14:07 UTC, ievetrovdev requested changes

2024-05-09 14:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task2.kt
> +    if (userAnswer == "да")
Давай еще учтем разный регистр, который может быть введен пользователем. Можно использовать метод сравнения у которого есть свойство ignoreCase

2024-05-09 14:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task2.kt
> +        return
странная конструкция, в else ничего нет. можно его не писать а код ниже перенести в if, будет аккуратнее

2024-05-09 14:37 UTC, GroovSt commented on src/main/kotlin/lesson_9/lesson9_task2.kt
> +        return
return завершает программу согласно условию: "- если пользователь ввел “нет” или что-то иное – заверши программу, если пользователь ввел “да” – запроси: "Какой ингредиент вы хотите добавить?";"

2024-05-10 06:26 UTC, ievetrovdev approved these changes

2024-05-11 12:11 UTC, merged